const fs = require('fs');
const content = fs.readFileSync('src/CampaignsPage.jsx', 'utf8');
const tags = content.match(/<([A-Z][a-zA-Z0-9]*)/g).map(s => s.slice(1));
const importMatch = content.match(/import\s+{([^}]+)}\s+from\s+['"]lucide-react['"]/);
const imports = importMatch ? importMatch[1].split(',').map(s => s.trim()) : [];
const used = [...new Set(tags)];
const missing = used.filter(t => !imports.includes(t) && !['Sidebar', 'NotificationIcon'].includes(t) && !t.startsWith('motion') && !['Link', 'LinkIcon'].includes(t));
console.log('Used:', used);
console.log('Imported:', imports);
console.log('Missing:', missing);
